### ISSUE TITLE
Base path can not be root

### ISSUE THREAD

**Issue by dfross** [CharlGottschalk/coppersmith#2]
How can I define a root path in my coppersmith.json file? I have tried `"./"`, but that breaks menu links.

**Comment by CharlGottschalk** [comment]
Urls are absolute so relative urls (`./`) won't work.

If you want to open the generated site please use the full path to your build folder i.e. `C:\dev\coppersmith-test\build` for the time being.

I will update the package to include allowances for local and production paths.
