### ISSUE TITLE
Issue after installing

### ISSUE THREAD

**Issue by damienvdw** [CharlGottschalk/coppersmith#3]
Hi,

I have installed successfully the project using `npm install -g coppersmith` as recommended.

However, when I try to run `copper -v` or `copper init`, I got this message :

> env: node\r: No such file or directory

Any ideas on how to fix this ?

**Comment by CharlGottschalk** [comment]
Hi @damienvdw 

That might have to do with the fact that the scripts were created on Windows and contain DOS style newlines `\r\n` instead of only `\n`.

What OS are you using?

**Comment by damienvdw** [comment]
I'm using MacOs.

Is there a simple way to fix this new line problem ?

**Comment by CharlGottschalk** [comment]
@damienvdw 

I did an update and converted the line endings from DOS to Unix.

Would you mind running `npm install -g coppersmith` to get the update and try again?

Please let me know whether it is fixed on your end.

**Comment by damienvdw** [comment]
@CharlGottschalk 

As of version 1.2.2, the issue is fixed and I can run `copper` cmd properly.

Thanks for the support !
