### ISSUE TITLE
copper init results in "env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by mtz** [CharlGottschalk/coppersmith#4]
Hi,

i would like to test coppersmith. but after installing coppersmith globally (yarn/npm) via documentation page i get the following error after "copper init":

env: node\r: No such file or directory

I'm using macosx "el capitan", 10.11.6 (15G1217)

thanks for help
mtz

**Comment by CharlGottschalk** [comment]
Hi @mtz 

Did you run the `copper init` command inside an empty folder?
If so, would you mind running `npm init` inside your project folder first and then `copper init` to see if that solves the problem?

**Comment by mtz** [comment]
Hi @CharlGottschalk 

yes, i've create an new empty folder, initialize by npm init and following commands. the errormessage appears always.

i've read some articles about this case and probably some file inside your project are saved with LF what my osx doesn't understand.

please let me know where i can find the files on my system. perhaps, if i open the files by vi with proper lineending config i can figure out if that is the problem.

**Comment by CharlGottschalk** [comment]
It should be located in the global npm folder at `/usr/local/lib/node_modules`.

I will check the line-endings on my side.

**Comment by CharlGottschalk** [comment]
The line endings were indeed `Windows`.

I converted all files to `Unix` line endings and published a new release ([v1.2.9](https://github.com/CharlGottschalk/coppersmith/releases/tag/v1.2.9)).

If you don't mind, please run an update to get the latest release, and let me know if it fixed the issue on your side:

`npm update -g coppersmith`

**Comment by mtz** [comment]
now copper init starts proper. the initially bug is not present anymore.

i answer the first 2 questions. after answering the third question (Where would you like your generated files to go?) i keep the default but i get the following error:

(node:52538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'split' of undefined

**Comment by CharlGottschalk** [comment]
I apologize @mtz 

You must be frustrated by now.
I removed a package which seemed to have thrown the error.

Please type something when asked for the build folder and see if that works, otherwise, please run an update to get version [v1.2.11](https://github.com/CharlGottschalk/coppersmith/releases/tag/v1.2.11)

**Comment by mtz** [comment]
Sorry for the delay. i went to an conference last days. 

With the new version 1.2.13 i got the initial problem back again (env: node\r: No such file or directory).

**Comment by CharlGottschalk** [comment]
It was the line endings again.

Just released [v1.2.14](https://github.com/CharlGottschalk/coppersmith/releases/tag/v1.2.14) with corrected line endings.

Please run `npm install -g coppersmith`.

**Comment by mtz** [comment]
hi,

with release v1.2.14 everything is fine. the app is working as expected. 
thanks.

**Comment by CharlGottschalk** [comment]
Good to hear @mtz 

Thanks for your patience.
